import type { Metadata } from "next";
import Link from "next/link";
import LegalPage from "@/components/LegalPage";
export const metadata: Metadata = { title: "Privacy policy", alternates: { canonical: "/privacy" } };
export default function Page() { return <LegalPage title="Privacy policy" intro="How VantriqAI handles information when you browse this website, send a brief or use our assistant.">
<h2>Who this notice covers</h2><p>VantriqAI is the business operating this public website. This notice applies to visitors, people sending enquiries and users of our public assistant. For a customer’s own agent or portal, that customer’s notice and the relevant service agreement also apply. Contact the VantriqAI team through our <Link href="/contact">contact page</Link> or published WhatsApp number for privacy questions and to identify the contracting entity for a proposed service.</p>
<h2>Information you provide</h2><p>When you send a brief, we receive your name, business, contact details, selected region and the information you type. When you use the assistant, your messages and conversation identifier are processed to answer questions, capture a requested lead or arrange a meeting. Please do not submit passwords, full payment-card details, identity documents or sensitive medical information.</p>
<h2>How we use it</h2><p>We use your information to respond to your enquiry, prepare a proposal, fulfil requested appointments, operate and secure the service and maintain the relevant customer record. Sending an enquiry is not permission for unrelated promotional messages. Where marketing permission is needed, it must be obtained separately; you can ask us to stop promotional contact.</p>
<h2>Why we process information</h2><p>Where applicable data-protection law requires a lawful basis, optional analytics rely on consent. Enquiry handling and requested proposals may involve steps you ask us to take before entering a contract; delivering an agreed service involves contractual necessity. Operating the website, securing systems and managing routine business correspondence may involve legitimate interests, balanced against your rights. Records required by law are retained for legal obligations. Any separate marketing or sensitive-data processing requires its own appropriate basis. Simply browsing does not give blanket permission for every use of your information.</p>
<h2>Required and optional information</h2><p>The brief form needs your name and a way to contact you so we can respond. Business details and notes help us understand the request. Providing information is voluntary, but we may be unable to answer, prepare a suitable quote or deliver a requested action without the necessary details. Rejecting optional analytics does not affect these services.</p>
<h2>Service providers and disclosures</h2><p>Enquiries are processed through our customer-record and business administration systems. Assistant messages and conversation identifiers are handled by our assistant service and its configured AI providers. Authorised hosting, document-storage, communications, calendar and technical-support providers may process information needed to deliver the requested interaction. Access and disclosure should be limited to the relevant purpose. Information may also be disclosed where required by law or necessary to address fraud, misuse or legal claims. Ask us for information about the recipients relevant to your interaction or proposed deployment. Following a WhatsApp or social-media link takes you to a separate provider whose terms and privacy notice apply.</p>
<h2>International processing</h2><p>Hosting and configured service providers may process information outside your country. Applicable legal requirements depend on the locations, data and provider involved. For a customer deployment, destination countries and any required transfer safeguards must be identified in the agreed data-processing arrangements before processing begins. Contact us for details about a specific interaction or deployment; this notice does not claim that an adequacy decision, particular contractual safeguard or certification applies to every provider.</p>
<h2>Optional website analytics</h2><p>Only if you accept optional analytics, we count page views, chat opens, WhatsApp clicks and successful briefs. Counts are grouped by calendar day, website section, Pakistan or Global site version, and approximate country/city. If you consent, the website server passes your network IP address to our CRM over HTTPS for a local GeoLite location lookup. No external location service receives the visitor IP from this lookup. The analytics system then discards the address and stores only aggregate location counts, without coordinates. Network location is approximate and can differ from your physical city, especially when using mobile networks or VPNs. We do not put names, messages, phone numbers, visitor identifiers, full URLs, query strings or referrers into these analytics. They measure activity among opted-in visitors, not unique people or a verified sales funnel. Network and hosting services may separately process IP addresses and technical logs for delivery, security and diagnostics.</p>
<h2>Storage and retention</h2><p>Your privacy choice is stored in your browser for 180 days. Aggregate analytics are retained for up to 180 days. Enquiry, conversation and customer records are retained according to the purpose of the interaction, your service agreement and applicable recordkeeping requirements; these do not share the analytics retention period. Contact us for details about a specific record.</p>
<h2>Your choices and requests</h2><p>Use “Privacy preferences” in the footer to withdraw analytics consent for future activity. Withdrawal does not invalidate processing that occurred beforehand. Past aggregate counts cannot be tied to you for removal. Depending on applicable law and the processing involved, you may request access, correction, deletion, restriction or portability of your personal information. Deletion may be limited where records must be kept for legal obligations or claims. Contact the team through our <Link href="/contact">contact page</Link> or published WhatsApp contact, describe your request and provide enough information to locate the relevant interaction. We may request proportionate identity verification and respond within the applicable legal time limits.</p>
<h2>Objections, marketing and complaints</h2><p>You may object to processing based on legitimate interests where applicable, and ask us to stop direct marketing. Tell the team which contact channel or processing you want stopped. You can raise a privacy concern with us and, where applicable, with the competent authority in your jurisdiction. People whose processing falls within UK data-protection law can contact the <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noopener noreferrer">Information Commissioner’s Office</a>. This reference does not imply that UK law applies to every website visitor.</p>
<h2>AI conversations and consequential decisions</h2><p>The public assistant uses automated processing to generate responses, understand requests and help with enquiries or appointments. It can make mistakes. Ask for a person to review important information or an action. It is not intended to decide eligibility for employment, credit, healthcare or other matters with legal or similarly significant effects. A customer seeking such processing needs a separate legal and deployment assessment, appropriate notices and human oversight.</p>
<h2>Security and sensitive information</h2><p>Use our published contact channels to report a suspected privacy or security issue. Do not send credentials, full payment-card data or unnecessary identity documents through the public chat or brief form. Customer-specific security controls, access permissions, incident cooperation and confidentiality requirements should be documented in the service agreement. No internet service can promise protection against every risk, and this notice does not claim an unverified security certification.</p>
<h2>Children</h2><p>This website promotes business services and is not directed at children. Do not submit a child’s personal information through the public assistant or brief form. If you believe such information has been provided, contact us so we can assess the record and appropriate action.</p>
<h2>Customer deployments and updates</h2><p>This notice covers our public website. A customer’s own agent deployment also requires that customer’s privacy information and service agreement. If our data practices change, we will update this page and request new consent where needed.</p>
</LegalPage>; }
