import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";
export const metadata: Metadata = { title: "Privacy policy", alternates: { canonical: "/privacy" } };
export default function Page() { return <LegalPage title="Privacy policy" intro="How VantriqAI handles information when you browse this website, send a brief or use our assistant.">
<h2>Information you provide</h2><p>When you send a brief, we receive your name, business, contact details, selected region and the information you type. When you use the assistant, your messages and conversation identifier are processed to answer questions, capture a requested lead or arrange a meeting. Please do not submit passwords, full payment-card details, identity documents or sensitive medical information.</p>
<h2>How we use it</h2><p>We use your information to respond to your enquiry, prepare a proposal, fulfil requested appointments, operate and secure the service and maintain the relevant customer record. Sending an enquiry is not permission for unrelated promotional messages. Where marketing permission is needed, it must be obtained separately; you can ask us to stop promotional contact.</p>
<h2>Service providers and destinations</h2><p>Briefs are sent to our CRM. An optional Google Sheet copy may be used where configured. Assistant messages are handled by our automation service and the AI providers configured for it. Hosting, communications and authorised service providers may process information to provide these services, including outside your country. Following a WhatsApp or social-media link takes you to a separate provider whose terms and privacy notice apply.</p>
<h2>Optional website analytics</h2><p>Only if you accept optional analytics, we count page views, chat opens, WhatsApp clicks and successful briefs. Counts are grouped by calendar day, website section and Pakistan or Global site. We do not put names, messages, phone numbers, visitor identifiers, full URLs, query strings or referrers into these analytics. They measure activity among opted-in visitors, not unique people or a verified sales funnel. Network and hosting services may separately process IP addresses and technical logs for delivery, security and diagnostics.</p>
<h2>Storage and retention</h2><p>Your privacy choice is stored in your browser for 180 days. Aggregate analytics are retained for up to 180 days. Enquiry, conversation and customer records are retained according to the purpose of the interaction, your service agreement and applicable recordkeeping requirements; these do not share the analytics retention period. Contact us for details about a specific record.</p>
<h2>Your choices and requests</h2><p>Use “Privacy preferences” in the footer to withdraw analytics consent for future activity. Past aggregate counts cannot be tied to you for removal. Depending on applicable law, you may request access, correction, deletion or restriction of your personal information and raise a concern with the relevant authority. Contact the team through our contact page or the published WhatsApp contact; we may need to verify your identity before acting.</p>
<h2>Customer deployments and updates</h2><p>This notice covers our public website. A customer’s own agent deployment also requires that customer’s privacy information and service agreement. If our data practices change, we will update this page and request new consent where needed.</p>
</LegalPage>; }
