// Real SQL + HTTP against an isolated database; never touches customer data.
const assert=require('node:assert/strict');
const fs=require('node:fs');const {randomUUID}=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite');const express=require('express');
const pg=new PGlite();let tail=Promise.resolve();
const acquire=async()=>{const prior=tail;let release;tail=new Promise(r=>release=r);await prior;return {query:(s,p)=>pg.query(s,p),release};};
const db={query:(s,p)=>pg.query(s,p),pool:{connect:acquire}};
require.cache[require.resolve('../src/db')]={exports:db};
const {errorHandler}=require('../src/utils/asyncErrors');
const P=require('../src/utils/portalLeads');const cal=require('../src/utils/calendar');
const {requirePortalSession}=require('../src/middleware/portalAuth');
const a=randomUUID(),b=randomUUID(),own=randomUUID(),prospect=randomUUID(),agent=randomUUID();let server;
(async()=>{
  await pg.exec(`create table sales_reps(id uuid primary key,name text,email text,active boolean);
    create table clients(id uuid primary key,name text,company text,email text,phone text,source text,external_ref text unique,
    owner_rep_id uuid references sales_reps(id),sales_stage text,stage text default 'lead',is_internal boolean default false,
    portal_username text,portal_password_hash text,notes text default '',updated_at timestamptz default now());
    create table client_agents(id uuid primary key,client_id uuid references clients(id),external_ref text unique);
    create table client_stage_history(client_id uuid,from_stage text,to_stage text,comment text);
    create table portal_sessions(token text primary key,client_id uuid references clients(id),expires_at timestamptz,last_seen_at timestamptz);`);
  const schema=fs.readFileSync('db/schema.sql','utf8');const migration=schema.slice(schema.indexOf('-- CRM calendar and explicit sales ownership.'),schema.indexOf('-- Pulse measurements are separate'));
  await pg.exec(migration);await pg.exec(migration);
  const workspace=fs.readFileSync('db/portal-workspace.sql','utf8');await pg.exec(workspace);await pg.exec(workspace);
  for(const [id,name,internal] of [[a,'Customer A',false],[b,'Customer B',false],[own,'VantriqAI',true],[prospect,'Existing prospect',false]])await pg.query('insert into clients(id,name,company,is_internal,portal_username) values($1,$2,$2,$3,$2)',[id,name,internal]);
  await pg.query('insert into client_agents values($1,$2,$3)',[agent,a,'agent-a']);
  await pg.query("insert into portal_sessions values('session-a',$1,now()+interval '1 day',null),('session-b',$2,now()+interval '1 day',null)",[a,b]);
  const app=express();app.use(express.json());app.use('/api/portal',requirePortalSession,require('../src/routes/portalWorkspace'));
  app.use('/api/calendar',(req,res,next)=>{req.user={email:'admin@example.test'};next();},require('../src/routes/calendar'));
  app.use('/api/webhooks',require('../src/routes/usage'));app.use(errorHandler);
  server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));const base='http://127.0.0.1:'+server.address().port;
  async function call(path,method='GET',body,token='session-a'){
    const res=await fetch(base+path,{method,headers:{'content-type':'application/json',authorization:'Bearer '+token},body:body?JSON.stringify(body):undefined});
    const data=await res.json().catch(()=>null);return {status:res.status,data};
  }
  assert.equal((await call('/api/portal/leads','GET',null,'')).status,401);
  const la=(await call('/api/portal/leads','POST',{name:'Ayesha',phone:'03001234567',company:'Acme',client_id:b})).data.lead;
  assert.equal(la.client_id,a,'body cannot override the session tenant');
  const lb=(await call('/api/portal/leads','POST',{name:'Other Ayesha',phone:'03001234567'},'session-b')).data.lead;
  assert.notEqual(la.id,lb.id,'same phone is independent in different businesses');
  assert.equal((await call('/api/portal/leads/'+lb.id)).status,404);
  assert.equal((await call('/api/portal/leads/'+lb.id,'PATCH',{status:'won'})).status,404);
  const list=await call('/api/portal/leads?client_id='+b);assert.equal(list.data.total,1);assert.equal(list.data.leads[0].id,la.id);assert.deepEqual(list.data.summary,{total:1,open:1,won:0,due:0,unassigned:1});
  const filtered=await call('/api/portal/leads?status=won');assert.equal(filtered.data.total,0);assert.equal(filtered.data.summary.open,1,'summary covers own whole account even when list is filtered');
  assert.equal((await call('/api/portal/leads/'+la.id,'PATCH',{status:'qualified',assigned_to:'Ali',next_action:'Prepare demo'})).status,200);
  const date=new Date(Date.now()+3*86400000);date.setUTCHours(5,0,0,0);
  const slot={lead_id:la.id,title:'Discovery demo',starts_at:date.toISOString(),ends_at:new Date(+date+1800000).toISOString(),kind:'demo',channel:'website',external_id:'tenant-a-booking'};
  const made=await call('/api/portal/calendar','POST',slot);assert.equal(made.status,201);const e=made.data.event;
  assert.equal((await call('/api/portal/calendar','POST',slot)).status,200);
  assert.equal((await call('/api/portal/calendar','POST',{...slot,title:'Different'})).status,409);
  assert.equal((await call('/api/portal/calendar','POST',{...slot,external_id:'clash',status:'confirmed'})).status,409);
  assert.equal((await call('/api/portal/calendar','POST',{...slot,lead_id:lb.id,external_id:'wrong-tenant'})).status,404);
  const range=new URLSearchParams({from:new Date(+date-86400000).toISOString(),to:new Date(+date+86400000).toISOString()});
  assert.equal((await call('/api/portal/calendar?'+range,'GET',null,'session-b')).data.length,0);
  assert.equal((await call('/api/portal/calendar/'+e.id,'PATCH',{status:'cancelled'},'session-b')).status,404);
  assert.equal((await call('/api/portal/calendar/'+e.id,'PATCH',{status:'confirmed'})).status,200);
  assert.equal((await cal.listEvents(Object.fromEntries(range))).find(x=>x.id===e.id).status,'confirmed','portal update visible in CRM');
  assert.equal((await call('/api/calendar/'+e.id,'PATCH',{status:'completed',outcome:'Send quote'})).status,200);
  let d=(await call('/api/portal/leads/'+la.id)).data;
  assert.equal(d.appointments[0].status,'completed','CRM update visible in portal');assert.equal(d.lead.status,'qualified','meeting outcome does not change sales status');
  assert.ok(d.history.some(h=>h.details.outcome==='Send quote'&&h.actor==='admin@example.test'));
  assert.equal((await call('/api/portal/calendar/'+e.id,'PATCH',{status:'scheduled',starts_at:new Date(+date+3600000).toISOString(),ends_at:new Date(+date+5400000).toISOString()})).status,200);
  d=(await call('/api/portal/leads/'+la.id)).data;assert.ok(d.history.some(h=>h.action==='meeting_rescheduled'));
  const la2=(await P.createLead(a,{name:'Bilal',phone:'03009876543'},'tester')).lead;
  await P.updateLead({id:a},la2.id,{assigned_to:'Ali'},'tester');
  await assert.rejects(()=>P.createEvent({id:a},{...slot,lead_id:la2.id,external_id:'owner-clash',starts_at:new Date(+date+3600000).toISOString(),ends_at:new Date(+date+5400000).toISOString()},'tester'),err=>err.status===409);
  const old=await cal.createEvent({...slot,client_id:prospect,external_id:'legacy'},'old agent');
  await P.syncInternal({id:own,is_internal:true});
  const ownLeads=await P.listLeads({id:own,is_internal:true});assert.ok(ownLeads.leads.some(l=>l.crm_client_id===prospect));
  const ownEvents=await P.listEvents({id:own,is_internal:true},Object.fromEntries(range));assert.ok(ownEvents.some(x=>x.id===old.event.id));
  assert.equal((await P.listEvents({id:a},Object.fromEntries(range))).some(x=>x.id===old.event.id),false,'old sales pipeline never appears in customer A');
  const capture=await call('/api/webhooks/lead','POST',{agent_ref:'agent-a',external_ref:'visitor-a',name:'Website lead',notes:'Interested'});assert.equal(capture.status,201);assert.equal(capture.data.tenant_client_id,a);
  const retry=await call('/api/webhooks/lead','POST',{agent_ref:'agent-a',external_ref:'visitor-a',name:'Wrong new name'});assert.equal(retry.data.lead_id,capture.data.lead_id);
  assert.equal((await P.detail({id:a},capture.data.lead_id)).lead.name,'Website lead');
  assert.equal((await call('/api/webhooks/lead','POST',{agent_ref:'agent-a',tenant_client_id:b,phone:'03001234567'})).status,400);
  const booking=await call('/api/webhooks/appointment','POST',{...slot,lead_id:capture.data.lead_id,agent_ref:'agent-a',external_id:'agent-booking'});assert.equal(booking.status,201);
  const tenantBBooking=await call('/api/portal/calendar','POST',{...slot,lead_id:lb.id},'session-b');assert.equal(tenantBBooking.status,201,'same provider booking id is independent in each tenant');
  const exportRes=await fetch(base+'/api/portal/calendar/export?'+range,{headers:{authorization:'Bearer session-a'}});assert.equal(exportRes.status,200);const ics=await exportRes.text();assert.match(ics,/BEGIN:VCALENDAR/);assert.doesNotMatch(ics,/Other Ayesha|Existing prospect/);
  assert.equal((await call('/api/portal/leads/'+la.id,'PATCH',{client_id:b})).status,400);
  console.log('Portal workspace checks passed: repeatable migration, two-customer isolation, pagination, shared CRM statuses, history, booking conflicts, legacy internal bridge, agent capture/retries and private ICS export.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(server)await new Promise(r=>server.close(r));await pg.close();});
