const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {randomUUID}=require('node:crypto');const {PGlite}=require('@electric-sql/pglite');
(async()=>{
 const pg=new PGlite();require.cache[require.resolve('../src/db')]={exports:{query:(q,p)=>pg.query(q,p)}};
 const {validatePulse,buildPulseAdvanced,pulseAdvanced}=require('../src/utils/pulseAdvanced');
 for(const bad of [{first_response_ms:-1},{deal_won:'true'},{cost_pkr:Infinity},{intent:'invented'},{secret:'x'},{}])assert.throws(()=>validatePulse(bad));
 const client=randomUUID(),other=randomUUID(),agent=randomUUID(),otherAgent=randomUUID();
 await pg.exec(`create table clients(id uuid primary key,company text,external_ref text);create table client_agents(id uuid primary key,client_id uuid references clients(id),name text,external_ref text);
 create table usage_events(id uuid default gen_random_uuid(),client_id uuid,session_id text,agent_id uuid,channel text,occurred_at timestamptz,handoff boolean);`);
 const migration='-- Pulse measurements are separate'+fs.readFileSync(require.resolve('../db/schema.sql'),'utf8').split('-- Pulse measurements are separate')[1];
 await pg.exec(migration);await pg.exec(migration);
 await pg.query("insert into clients values($1,'A','a'),($2,'B','b')",[client,other]);
 await pg.query("insert into client_agents values($1,$2,'First agent','agent-a'),($3,$4,'Foreign agent','agent-b')",[agent,client,otherAgent,other]);
 await pg.query("insert into usage_events(client_id,session_id,agent_id,channel,occurred_at,handoff) values($1,'s1',$2,'whatsapp',now()-interval '1 day',false),($1,'s1',$2,'whatsapp',now(),false),($1,'s2',$2,'web',now(),true),($3,'foreign',$4,'web',now(),true)",[client,agent,other,otherAgent]);
 const express=require('express'),app=express();app.use(express.json());app.use(require('../src/routes/usage'));
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));
 const post=async body=>{const r=await fetch('http://127.0.0.1:'+server.address().port+'/pulse-event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};};
 const event={client_id:client,agent_id:agent,event_id:'e1',session_id:'s1',data:{first_response_ms:1000,qualified_lead:true,cost_pkr:2,intent:'pricing'}};
 assert.equal((await post(event)).status,201);assert.equal((await post(event)).data.duplicate,true);
 assert.equal((await post({...event,data:{qualified_lead:false}})).status,409);
 assert.equal((await post({...event,event_id:'bad',agent_id:otherAgent})).status,400);
 assert.equal((await post({...event,event_id:'bad',data:{first_response_ms:-2}})).status,400);
 assert.equal((await post({...event,event_id:'future',occurred_at:'2999-01-01'})).status,400);
 assert.equal((await post({external_ref:'a',event_id:'e2',session_id:'s2',data:{first_response_ms:3000,confirmed_resolution:true,meeting_booked:true,deal_won:true,handoff_reason:'<img onerror=x>',status:'failure',attributed_revenue_pkr:100}})).status,201);
 await post({client_id:other,event_id:'e3',session_id:'foreign',data:{qualified_lead:true,cost_pkr:999999}});
 const bounds={cur_start:new Date(Date.now()-3*86400000).toISOString()};
 const own=await pulseAdvanced(client,bounds),all=await pulseAdvanced(null,bounds);
 assert.equal(own.conversations,2);assert.equal(own.outcomes.qualified,1);assert.equal(own.response.median_seconds,2);assert.equal(own.response.p95_seconds,2.9);
 assert.equal(own.agents[0].qualification_pct,100);assert.equal(own.agents[0].qualification_reported,1);assert.equal(own.agents[0].handoff_pct,50);assert.equal(own.agents[0].resolved,1);assert.equal(own.agents[0].resolution_reported,1);
 assert.ok(!('value' in own));assert.ok(!('health' in own));assert.doesNotMatch(JSON.stringify(own),/Foreign agent|foreign|999999/);
 assert.equal((await pg.query('select count(*) n from usage_events')).rows[0].n,4,'Pulse events do not add billable usage');assert.equal(all.value.cost,1000001);assert.equal(all.health.failure,1);assert.equal((await pg.query('select count(*) n from pulse_events')).rows[0].n,3);
 const duplicated=buildPulseAdvanced([{client_id:'a',session_id:'s',channel:'web'}],[{client_id:'a',session_id:'s',event_id:'x',data:{cost_pkr:2}},{client_id:'a',session_id:'s',event_id:'x',data:{cost_pkr:2}}]);assert.equal(duplicated.value.cost,2);assert.equal(duplicated.response.median_seconds,null);
 const ctx=vm.createContext({window:{},console});vm.runInContext(fs.readFileSync(require.resolve('../public/analytics-view.js'),'utf8'),ctx);
 const metric={current:0,previous:0,delta_pct:null};
 const dashboard={advanced:own,grain:'month',time_zone:'Asia/Karachi',period:{current_label:'This month',previous_label:'last month',window_label:'Last 12 months',elapsed_pct:10},series:[],quota:null,window_totals:{conversations:0},kpis:{conversations:metric,new_contacts:metric,returning_contacts:metric,messages:metric,messages_per_conversation:metric},channels:[],agents:[],insights:[],satisfaction:null};
 const html=ctx.window.VQA.conversationsHTML(dashboard,{audience:'portal'});assert.ok(html.includes('Agent performance matrix'));assert.ok(html.includes('Response speed'));assert.ok(html.includes('New contacts'));assert.doesNotMatch(html,/Automation health|Reported business value|New contacts \(leads\)|<img onerror=x>/);assert.match(html,/&lt;img/);
 dashboard.advanced=all;const staff=ctx.window.VQA.conversationsHTML(dashboard,{audience:'platform'});assert.match(staff,/Automation health|Reported business value/);
 const ExcelJS=require('exceljs'),wb=new ExcelJS.Workbook();require('../src/utils/analyticsReport').appendPulseAdvancedReport(wb,own,'A','This month');const check=new ExcelJS.Workbook();await check.xlsx.load(await wb.xlsx.writeBuffer());assert.ok(check.getWorksheet('Pulse outcomes'));assert.ok(check.getWorksheet('Pulse service'));assert.ok(!check.getWorksheet('Pulse operations'));
 const serialized=JSON.stringify(own);assert.ok(!serialized.includes('s1'));assert.ok(!serialized.includes(client));
 await new Promise(r=>server.close(r));await pg.close();console.log('PASS: Pulse event validation/idempotency, ownership, cohort counts, response percentiles, unknown coverage, tenant isolation, private diagnostics, rendering and Excel export.');
})().catch(err=>{console.error(err);process.exit(1);});
