// Real SQL and HTTP regression checks; isolated database, no production traffic.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { randomUUID } = require('node:crypto');
const { PGlite } = require('@electric-sql/pglite');
const pg = new PGlite();
let tail = Promise.resolve();
async function acquire() { const previous=tail; let release; tail=new Promise(r=>release=r); await previous; return { query:(s,p)=>pg.query(s,p), release }; }
const db={ query:(s,p)=>pg.query(s,p), pool:{connect:acquire} };
require.cache[require.resolve('../src/db')]={exports:db};
require.cache[require.resolve('../src/utils/securityAlerts')]={exports:{alertOwner:()=>{}}};
require.cache[require.resolve('../src/utils/mailer')]={exports:{mailConfigured:()=>false,sendMail:async()=>{},otpEmail:()=>({}),resetEmail:()=>({}),invoiceEmail:()=>({}),breakglassEmail:()=>({})}};
const {errorHandler}=require('../src/utils/asyncErrors');
const express=require('express');
const {hashPassword,verifyPassword}=require('../src/utils/password');
const {currentCode,randomSecret}=require('../src/utils/totp');
const {requireScope}=require('../src/middleware/auth');
const {securityHeaders,requireAdmin,takeLimit}=require('../src/middleware/security');
const {issueReset,redeemReset}=require('../src/utils/resets');
const {issuePreview,validPreview}=require('../src/utils/surveyPreview');
let server;
(async()=>{
 await pg.exec(`create table internal_users(id uuid primary key,email text unique,name text,role text,active boolean default true,password_hash text,is_owner boolean default false,must_change_password boolean default false,must_setup_totp boolean default false,totp_enabled boolean default false,totp_secret text,password_set_by text,last_login_at timestamptz);
 create table staff_sessions(token text primary key,user_id uuid,expires_at timestamptz,last_seen_at timestamptz);
 create table login_challenges(id uuid primary key default gen_random_uuid(),user_id uuid,code_hash text,method text,expires_at timestamptz,attempts integer default 0,consumed boolean default false);
 create table clients(id uuid primary key,company text,name text,email text,portal_username text,portal_password_hash text);
 create table password_resets(id uuid primary key default gen_random_uuid(),subject_type text,subject_id uuid,token_hash text,expires_at timestamptz,used_at timestamptz);`);
 const migration=fs.readFileSync(require('node:path').join(__dirname,'../db/security-hardening.sql'),'utf8');
 await pg.exec(migration); await pg.exec(migration);
 const uid=randomUUID(),pass='InitialPassword123!',newpass='ReplacementPassword456!';
 await pg.query(`insert into internal_users(id,email,name,role,password_hash,is_owner,must_change_password,must_setup_totp) values($1,'ceo@vantriqai.com','Owner','admin',$2,true,true,true)`,[uid,hashPassword(pass)]);
 async function session(token){await pg.query("insert into staff_sessions values($1,$2,now()+interval '1 day',null)",[token,uid]);}
 await session('first'); await session('other');
 const app=express();app.use(securityHeaders);app.use(express.json({limit:'16kb'}));app.use('/api/auth',require('../src/routes/auth').router);
 app.get('/api/protected',requireScope('staff'),(req,res)=>res.json({ok:true}));
 app.post('/admin', (req,res,next)=>{req.user={role:req.header('x-role')};next();},requireAdmin,(req,res)=>res.json({ok:true}));
 const asRole=(req,res,next)=>{req.user={role:req.header('x-role')||'staff'};req.authKind=req.header('x-kind')||'session';req.apiKeyScope='automation';next();};
 app.use('/api/clients',asRole,require('../src/routes/clients'));
 app.use('/api/invoices',asRole,require('../src/routes/invoices'));
 app.use('/api/portal',require('../src/routes/portal'));
 const draft={slug:'private-draft',status:'draft',content:{intro:{en:'Confidential draft question'}},default_language:'en',display_name:'Private'};
 require.cache[require.resolve('../src/utils/surveys')]={exports:{getSurveyBySlug:async()=>draft,publicSurvey:x=>x,isClosed:()=>false,publicBase:()=>base,escapeHtml:x=>String(x||'')}};
 app.use('/api/public',require('../src/routes/publicSurveyApi'));
 app.use('/s',require('../src/routes/surveyPages'));
 app.use(errorHandler);server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const post=(p,b={},token='first',extra={})=>fetch(base+p,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token,...extra},body:JSON.stringify(b)});
 const probe=()=>fetch(base+'/api/protected',{headers:{authorization:'Bearer first'}});
 assert.equal((await probe()).status,403);
 assert.equal((await post('/api/auth/totp/setup',{password:pass})).status,403);
 assert.equal((await post('/api/auth/change-password',{current_password:pass,new_password:newpass})).status,200);
 assert.equal((await pg.query("select count(*)::int n from staff_sessions where token='other'")).rows[0].n,0);
 assert.equal((await probe()).status,403);
 assert.equal((await post('/api/auth/totp/setup',{})).status,401);
 let setup=await post('/api/auth/totp/setup',{password:newpass}); assert.equal(setup.status,200);let pending=(await setup.json()).secret;
 await session('other');
 assert.equal((await post('/api/auth/totp/confirm',{code:currentCode(pending)},'other')).status,400);
 assert.equal((await post('/api/auth/totp/confirm',{code:currentCode(pending)})).status,200);
 assert.equal((await probe()).status,200);
 assert.equal((await post('/api/auth/totp/disable',{password:newpass,current_code:currentCode(pending)})).status,403);
 assert.equal((await post('/api/auth/totp/setup',{password:newpass})).status,401);
 setup=await post('/api/auth/totp/setup',{password:newpass,current_code:currentCode(pending)});assert.equal(setup.status,200);const replacement=(await setup.json()).secret;
 const before=(await pg.query('select * from internal_users where id=$1',[uid])).rows[0]; assert.equal(before.totp_enabled,true);assert.equal(before.totp_secret,pending);assert.equal(before.pending_totp_secret,replacement);
 assert.equal((await post('/api/auth/totp/confirm',{code:currentCode(replacement)})).status,200);
 const challenge=randomUUID();await pg.query("insert into login_challenges(id,user_id,method,expires_at) values($1,$2,'totp',now()+interval '10 minutes')",[challenge,uid]);
 const responses=await Promise.all([post('/api/auth/verify',{challenge_id:challenge,code:currentCode(replacement)}),post('/api/auth/verify',{challenge_id:challenge,code:currentCode(replacement)})]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,400]);
 const reset=await issueReset('staff',uid);const redeemed=await Promise.all([redeemReset('staff',reset.token,'FinalPassword789!'),redeemReset('staff',reset.token,'AttackerPassword999!')]);assert.equal(redeemed.filter(x=>x.ok).length,1);
 const after=(await pg.query('select * from internal_users where id=$1',[uid])).rows[0];assert.equal(verifyPassword('FinalPassword789!',after.password_hash),true);assert.equal(after.pending_totp_secret,null);assert.equal((await pg.query('select count(*)::int n from staff_sessions')).rows[0].n,0);
 for(let i=0;i<10;i++)assert.equal((await post('/api/auth/login',{email:'missing@vantriqai.com',password:'wrong'})).status,401);
 const limited=await post('/api/auth/login',{email:'missing@vantriqai.com',password:'wrong'});assert.equal(limited.status,429);assert.ok(Number(limited.headers.get('retry-after'))>0);
 for(let i=0;i<3;i++)assert.equal((await post('/api/auth/forgot-password',{email:'missing@vantriqai.com'})).status,200);
 assert.equal((await post('/api/auth/forgot-password',{email:'missing@vantriqai.com'})).status,429);
 assert.equal((await post('/admin',{},'',{'x-role':'staff'})).status,403);assert.equal((await post('/admin',{},'',{'x-role':'admin'})).status,200);
 for(let i=0;i<10;i++)assert.equal((await post('/api/portal/login',{username:'missing',password:'wrong'})).status,401);
 assert.equal((await post('/api/portal/login',{username:'missing',password:'wrong'})).status,429);
 assert.equal((await post('/api/clients/'+uid+'/portal-credentials',{},'',{'x-role':'staff'})).status,403);
 const invoice=await fetch(base+'/api/invoices/'+uid+'/status',{method:'PATCH',headers:{'content-type':'application/json','x-kind':'apikey'},body:JSON.stringify({status:'paid'})});assert.equal(invoice.status,403);
 assert.equal((await fetch(base+'/api/public/surveys/private-draft?preview=1')).status,404);
 const page=await fetch(base+'/s/private-draft?preview=1');assert.ok(!(await page.text()).includes('Confidential draft question'));
 const signed=issuePreview('private-draft');assert.equal((await fetch(base+'/api/public/surveys/private-draft?preview=1&preview_token='+signed)).status,200);
 assert.ok((await (await fetch(base+'/s/private-draft?preview=1&preview_token='+signed)).text()).includes('Confidential draft question'));
 const token=issuePreview('private-draft');assert.equal(validPreview('private-draft',token),true);assert.equal(validPreview('different',token),false);assert.equal(validPreview('private-draft','1'),false);assert.equal(validPreview('private-draft',token+'a'),false);
 const limits=await Promise.all(Array.from({length:12},()=>takeLimit('race','identity',5,60)));assert.equal(limits.filter(x=>x.allowed).length,5);
 console.log('Security regression checks passed: setup enforcement, MFA replacement/session binding, session revocation, single-use OTP/reset races, durable throttles, admin restriction, signed previews, repeatable migration.');
})().catch(err=>{console.error(err);process.exitCode=1;}).finally(async()=>{if(server)await new Promise(r=>server.close(r));await pg.close();});
