const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {PGlite}=require('@electric-sql/pglite');
(async()=>{
 const pg=new PGlite();require.cache[require.resolve('../src/db')]={exports:{query:(q,p)=>pg.query(q,p)}};
 const {validateSiteEvent,recordSiteEvent,siteAnalytics,locationOf,websiteAnalytics}=require('../src/utils/siteAnalytics');
 for(const bad of [null,[],{},{event:'page_view',section:'home',region:'pk',client_ip:'not-an-ip'}, {event:'page_view',section:'home',region:'pk',email:'private'}, {event:'page_view',section:'phone-number',region:'pk'}, {event:'invented',section:'home',region:'pk'}]) assert.throws(()=>validateSiteEvent(bad));
 const sql='-- Opt-in public website activity:'+fs.readFileSync(require.resolve('../db/schema.sql'),'utf8').split('-- Opt-in public website activity:')[1];await pg.exec(sql);await pg.exec(sql);
 const express=require('express'),app=express();app.use(express.json());app.use(require('../src/routes/usage'));app.use('/analytics',require('../src/routes/analytics'));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));
 const post=body=>fetch('http://127.0.0.1:'+server.address().port+'/site-event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
 assert.equal((await post({event:'page_view',region:'pk',section:'products',email:'private'})).status,400);
 assert.equal((await post({event:'page_view',region:'pk',section:'products'})).status,200);
 await Promise.all(Array.from({length:12},()=>recordSiteEvent({event:'page_view',region:'pk',section:'products'})));
 await recordSiteEvent({event:'whatsapp_click',region:'global',section:'contact'});
 await pg.exec("insert into website_activity values(current_date-200,'pk','home','page_view',99)");
 await recordSiteEvent({event:'chat_open',region:'pk',section:'home'});
 const a=await siteAnalytics('2020-01-01T00:00:00Z');assert.equal(a.totals.page_view,13);assert.equal(a.totals.whatsapp_click,1);assert.equal(a.regions.pk.page_view,13);assert.equal(a.sections.products.page_view,13);assert.equal((await pg.query('select count(*) n from website_activity where day<current_date-180')).rows[0].n,0);
 assert.equal(locationOf('39.32.0.1').country,'PK');assert.ok(locationOf('39.32.0.1').city);
 for(const ip of [undefined,'invalid','127.0.0.1','10.0.0.1','::1'])assert.equal(locationOf(ip).country,'');
 assert.equal(locationOf('::ffff:8.8.8.8').country,'US');assert.equal(locationOf('2001:4860:4860::8888').country,'US');
 await recordSiteEvent({event:'page_view',region:'global',section:'products',client_ip:'39.32.0.1'});
 await recordSiteEvent({event:'brief_sent',region:'global',section:'contact',client_ip:'39.32.0.1'});
 await pg.exec("insert into website_activity values((now() at time zone 'Asia/Karachi')::date,'pk','resources','page_view',5)");
 await pg.exec("insert into website_location_activity values(current_date-200,'pk','home','page_view','PK','PB','Lahore',9)");
 const located=await websiteAnalytics({range:'30d'});
 assert.equal(located.website.totals.page_view,19);assert.equal(located.website.countries.find(r=>r.country==='PK').page_view,1);
 assert.equal(located.website.countries.find(r=>r.country==='').page_view,18);
 assert.equal(located.website.locations.find(r=>r.country==='PK').brief_sent,1);
 assert.ok(!JSON.stringify(located).includes('39.32.0.1'));assert.equal((await pg.query('select count(*) n from website_location_activity where day<current_date-180')).rows[0].n,0);
 assert.equal((await fetch('http://127.0.0.1:'+server.address().port+'/analytics/website?range=7d')).status,200);
 assert.equal((await fetch('http://127.0.0.1:'+server.address().port+'/analytics/website/report.xlsx?range=7d')).status,200);
 for(const range of ['today','7d','30d','90d','180d'])assert.equal((await websiteAnalytics({range})).range,range);
 assert.equal((await websiteAnalytics({range:'invalid'})).range,'30d');
 await pg.exec("insert into website_activity values((now() at time zone 'Asia/Karachi')::date-6,'pk','home','page_view',2),((now() at time zone 'Asia/Karachi')::date-7,'pk','home','page_view',3)");
 assert.equal((await websiteAnalytics({range:'today'})).website.totals.page_view,19);assert.equal((await websiteAnalytics({range:'7d'})).website.totals.page_view,21);assert.equal((await websiteAnalytics({range:'30d'})).website.totals.page_view,24);
 const ctx=vm.createContext({window:{},console});vm.runInContext(fs.readFileSync(require.resolve('../public/analytics-view.js'),'utf8'),ctx);
 const metric={current:0,previous:0,delta_pct:null};const d={website:a,grain:'month',time_zone:'Asia/Karachi',period:{current_label:'This month',previous_label:'Last month',window_label:'Last 12 months',elapsed_pct:10},series:[],window_totals:{conversations:0},kpis:{conversations:metric,new_contacts:metric,returning_contacts:metric,messages:metric,messages_per_conversation:metric},channels:[],agents:[],insights:[]};
 assert.match(ctx.window.VQA.conversationsHTML(d,{audience:'platform'}),/Website insights|Successful briefs/);assert.doesNotMatch(ctx.window.VQA.conversationsHTML(d,{audience:'portal'}),/Website insights|Successful briefs/);
 const siteHTML=ctx.window.VQA.websiteTrafficHTML(located,{onRange:'setWebsiteRange',onReport:'downloadAnalyticsReport'});
 assert.match(siteHTML,/Website traffic|Pakistan|Approximate visitor location/);assert.match(siteHTML,/Last 7 days/);assert.doesNotMatch(siteHTML,/39\.32\.0\.1/);
 const hostile={...located,website:{...located.website,locations:[{country:'PK',city:'<img onerror=x>',subdivision:'PB',page_view:1}]}};
 assert.doesNotMatch(ctx.window.VQA.websiteTrafficHTML(hostile),/<img onerror=x>/);
 const ExcelJS=require('exceljs'),wb=new ExcelJS.Workbook();require('../src/utils/analyticsReport').appendWebsiteReport(wb,a,'This month');const check=new ExcelJS.Workbook();await check.xlsx.load(await wb.xlsx.writeBuffer());assert.ok(check.getWorksheet('Website activity'));assert.ok(check.getWorksheet('Website locations'));
 const report=await require('../src/utils/analyticsReport').websiteReport({range:'7d'});assert.match(report.filename,/website-7d/);const rw=new ExcelJS.Workbook();await rw.xlsx.load(report.buffer);assert.equal(rw.getWorksheet('Website locations').rowCount>5,true);
 await new Promise(r=>server.close(r));await pg.close();console.log('PASS: website validation, atomic concurrent counts, local IPv4/IPv6 lookup, unknown historical data, location retention, ranges, private renderers and Excel exports.');
})().catch(e=>{console.error(e);process.exit(1)});
