import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";
export const metadata: Metadata = { title: "Cookies & browser storage", alternates: { canonical: "/cookies" } };
export default function Page() { return <LegalPage title="Cookies & browser storage" intro="Small browser records support privacy choices and chat. Optional measurement is always your choice.">
<h2>What this website uses</h2><p>Cookies are sent with browser requests; local storage stays in your browser until a page reads it. Both can remember information. Our current optional analytics use neither analytics cookies nor a persistent visitor identifier.</p>
<div className="legal-table"><table><thead><tr><th>Browser storage</th><th>Purpose</th><th>Duration</th></tr></thead><tbody><tr><td>Privacy preferences (local storage)</td><td>Your analytics choice, notice version and date saved</td><td>180 days, then we ask again</td></tr><tr><td>Chat session (session storage)</td><td>A conversation identifier and the messages of your current chat, so the conversation follows you between pages</td><td>Until you close the tab, start a new conversation or clear it in your browser</td></tr><tr><td>Chat prompt (session storage)</td><td>Remembers that the assistant’s one-time suggestion bubble was shown, so it does not appear again on this visit</td><td>Until you close the tab</td></tr></tbody></table></div>
<h2>Necessary storage and your control</h2><p>Privacy preferences remember your selection so we can honour it. Chat storage supports the conversation you request. These records serve different purposes from optional measurement; they are not advertising profiles. Local storage does not necessarily expire when you close a tab. You can clear it in your browser settings, which may reset preferences or the assistant’s conversation. The durations above describe browser records, not the retention of enquiry or customer records on our systems; see the <a href="/privacy">Privacy policy</a> for that distinction.</p>
<h2>Optional analytics</h2><p>Disabled by default. Accepting enables aggregate page-view, chat-open, WhatsApp-click and successful-brief counts by day, website section, website version and approximate country/city. Your network IP address is passed securely to our CRM for a local location lookup, then discarded from analytics processing. We store only aggregate location counts for up to 180 days, not IP addresses or coordinates. IP-based locations can differ from your actual city, especially on mobile networks or VPNs. No advertising pixel, visitor profile or cross-site tracking is installed. Rejecting optional analytics does not prevent browsing, chatting or sending a brief.</p>
<h2>Manage your choice</h2><p>Select “Privacy preferences” in the footer at any time. Rejecting stops future optional measurement immediately. You can also delete browser storage through your browser settings. If storage is blocked, your choice may last only for the current page. Changing devices or clearing storage means you may be asked again.</p>
<h2>Other services</h2><p>The CRM and customer portal have their own login and storage needs. External WhatsApp and social-media services may use their own cookies after you follow a link. Necessary hosting or security storage, if introduced by the infrastructure, serves delivery and protection rather than our optional analytics.</p>
</LegalPage>; }
